use super::*;
use crate::{no_walljump, walljump};

pub const CHECKS: [Check; 255] = [
    // Fire Keep
    Check {
        location: Location::Lab,
        context: Context::Starting,
        drop: Drop::Emote(Emote::Hello2),
        locks: &[],
    },
    Check {
        location: Location::Lab,
        context: Context::Starting,
        drop: Drop::Ability(Ability::Dash),
        locks: &[],
    },
    Check {
        location: Location::Bitoven,
        context: Context::Overworld("A01_FireKeep_EmoteStatue_Levitation"),
        drop: Drop::Emote(Emote::Levitation),
        locks: &[],
    },
    Check {
        location: Location::Bitoven,
        context: Context::Cutscene("NPC/Onops/MUSIC_Onops/Onop_Musicians/NPC_Onop_IO_Bitoven"),
        drop: Drop::Ore(500),
        locks: &[
            Lock::Location(Location::RustVillage),
            Lock::Item(Item::ComposerLetter),
        ],
    },
    Check {
        location: Location::KeepDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[no_walljump!(4, 0)])],
    },
    Check {
        location: Location::KeepVessel,
        context: Context::Overworld("Chest_A01_TempleGardens_Ability_SpinAttack2"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::KeepVessel,
        context: Context::Overworld("Chest_A02_Keep_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::KeepVessel,
        context: Context::Overworld("Pickup"),
        drop: Drop::Ore(250),
        locks: &[],
    },
    Check {
        location: Location::Shield,
        context: Context::Overworld("Chest_A02_Keep_Key_01"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[],
    },
    Check {
        location: Location::Shield,
        context: Context::Overworld("Chest_A01_Keep_Shield"),
        drop: Drop::Ability(Ability::Block),
        locks: &[],
    },
    Check {
        location: Location::FirstVoid,
        context: Context::Overworld("A01_FireKeep_EmoteStatue_Techno"),
        drop: Drop::Emote(Emote::Techno),
        locks: &[],
    },
    Check {
        location: Location::FirstVoid,
        context: Context::Overworld("Spirit_A02_RiverSpirit"),
        drop: Drop::Spirit(Spirit::RiverSpirit),
        locks: &[Lock::Movement(&[no_walljump!(2, 0), walljump!(0, 0)])],
    },
    Check {
        location: Location::Crates,
        context: Context::Overworld("Chest_A02_Keep_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Memorial,
        context: Context::Overworld("Chest_A02_GameIntro"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Memorial,
        context: Context::Overworld("Chest_A02_Sword_DiamondWings"),
        drop: Drop::Weapon(Weapon::DiamondWings),
        locks: &[],
    },
    Check {
        location: Location::Memorial,
        context: Context::Overworld("A02_FireKeep_EmoteStatue_Celebration"),
        drop: Drop::Emote(Emote::Celebration),
        locks: &[],
    },
    Check {
        location: Location::Memorial,
        context: Context::Overworld("Dance_Platform_Photo_Chest"),
        drop: Drop::Item(Item::Mandoline, 1),
        locks: &[Lock::Emote(Emote::Photo)],
    },
    // Arcane Tunnels
    Check {
        location: Location::ArcaneNorth,
        context: Context::Overworld("Pickup3"),
        drop: Drop::Ore(250),
        locks: &[],
    },
    Check {
        location: Location::ArcaneNorth,
        context: Context::Overworld("A02_Arcane_EmoteStatue_Windmill"),
        drop: Drop::Emote(Emote::Windmill),
        locks: &[],
    },
    Check {
        location: Location::ArcaneNorth,
        context: Context::Overworld("Chest_A02_NorthArcane_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 2),
        locks: &[],
    },
    Check {
        location: Location::ArcaneNorth,
        context: Context::Overworld("Chest_A02_NorthArcane_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Dance_Platform_KungFu_Chest"),
        drop: Drop::Item(Item::Boot, 1),
        locks: &[Lock::Emote(Emote::KungFu)],
    },
    Check {
        location: Location::Waterway,
        context: Context::Overworld("A02_Arcane_EmoteStatue_HatKid"),
        drop: Drop::Emote(Emote::HatKid),
        locks: &[],
    },
    Check {
        location: Location::WaterwayDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[
            Lock::Item(Item::SanctuaryStone),
            Lock::Movement(&[no_walljump!(0, 2)]),
        ],
    },
    Check {
        location: Location::Waterway,
        context: Context::Overworld("Pickup"),
        drop: Drop::Ore(400),
        locks: &[Lock::Location(Location::LakeMolva)],
    },
    Check {
        location: Location::Waterway,
        context: Context::Overworld("Chest_A02_Tunic_PureShadow"),
        drop: Drop::Tunic(Tunic::PureShadow),
        locks: &[Lock::Location(Location::Samael)],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Chest_A02_NorthArcane_Sword_Bloodstorm"),
        drop: Drop::Weapon(Weapon::BloodstormBlades),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Spirit_A02_ToxicRat"),
        drop: Drop::Spirit(Spirit::ToxicRat),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Chest_A02_SouthArcane_Key_01"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Dance_Platform_Celebration_Chest"),
        drop: Drop::Item(Item::Rice, 1),
        locks: &[Lock::Emote(Emote::Celebration)],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Chest_A02_SouthArcane_Loot_01"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSouth,
        context: Context::Overworld("Chest_A02_SouthArcane_Key_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneNorth,
        context: Context::Overworld("Pickup4"),
        drop: Drop::Ore(250),
        locks: &[Lock::Movement(&[walljump!(0, 4), no_walljump!(0, 8)])],
    },
    Check {
        location: Location::ArcaneNorth,
        context: Context::Overworld("Chest_A02_NorthArcane_Loot_04"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 4), no_walljump!(0, 8)])],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Chest_A01_Arcane_Spell"),
        drop: Drop::Ability(Ability::Spell),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Chest_A02_EastArcane_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Chest_A02_EastArcane_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Pickup_A02_SRF"),
        drop: Drop::Ore(300),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Pickup_A02_SRF2"),
        drop: Drop::Ore(200),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Shop(Shop::SpiritHunter, 0, 5500),
        drop: Drop::Spirit(Spirit::StormCentry),
        locks: &[Lock::Money(5500)],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Shop(Shop::SpiritHunter, 1, 3500),
        drop: Drop::Spirit(Spirit::BloodPhantom),
        locks: &[Lock::Money(3500)],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Shop(Shop::SpiritHunter, 2, 4500),
        drop: Drop::Spirit(Spirit::FrozenSoul),
        locks: &[Lock::Money(4500)],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Shop(Shop::SpiritHunter, 3, 2500),
        drop: Drop::Spirit(Spirit::ShadowGru),
        locks: &[Lock::Money(2500)],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Cutscene("NPC/SpiritHunter/NPC_SpiritHunter"),
        drop: Drop::Tunic(Tunic::ThiefsCloack),
        locks: &[Lock::SpiritHunter],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Chest_A02_EastArcane_Loot_05"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Chest_A02_EastArcane_Loot_04"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArcaneDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Chest_A02_EastArcane_Loot_03"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Pickup_A02_Arcane_SR_Loot"),
        drop: Drop::Ore(400),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    // AND THESE ONES ARE NAMED FINE???
    Check {
        location: Location::ArcaneSpiritHunter,
        context: Context::Overworld("Pickup_A02_Arcane_SR_Loot2"),
        drop: Drop::Ore(400),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    // Crossroads
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup49"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup47"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Well,
        context: Context::Overworld("Chest_A01_CrossRoads_Loot"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[
            Lock::Movement(&[no_walljump!(1, 0)]),
            Lock::Movement(&[no_walljump!(0, 2)]),
            Lock::Movement(&[walljump!(0, 0)]),
        ],
    },
    Check {
        location: Location::Well,
        context: Context::Overworld("Chest_A01_Well_SpinAttack"),
        drop: Drop::Ability(Ability::SpinAttack),
        locks: &[
            Lock::Movement(&[no_walljump!(1, 0)]),
            Lock::Movement(&[no_walljump!(0, 2)]),
            Lock::Movement(&[walljump!(0, 0)]),
        ],
    },
    Check {
        location: Location::Well,
        context: Context::Overworld("Pickup57"),
        drop: Drop::Ore(500),
        locks: &[
            Lock::Movement(&[no_walljump!(1, 0)]),
            Lock::Movement(&[no_walljump!(0, 2)]),
            Lock::Movement(&[walljump!(0, 0)]),
        ],
    },
    Check {
        location: Location::Well,
        context: Context::Overworld("Pickup60"),
        drop: Drop::Ore(500),
        locks: &[Lock::Movement(&[no_walljump!(0, 2)])],
    },
    Check {
        location: Location::Well,
        context: Context::Overworld("Pickup5"),
        drop: Drop::Ore(500),
        locks: &[
            Lock::Movement(&[no_walljump!(2, 2)]),
            Lock::Movement(&[walljump!(1, 2)]),
        ],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup7"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup14"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup15"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup11"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup12"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup56"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Chest_A01_CrossRoads_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Pickup50"),
        drop: Drop::Ore(50),
        locks: &[],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Chest_A01_CrossRoads_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Dance_Platform_Techno_Chest"),
        drop: Drop::Tunic(Tunic::Galaxy),
        locks: &[
            Lock::Emote(Emote::Techno),
            Lock::Movement(&[no_walljump!(0, 1)]),
        ],
    },
    Check {
        location: Location::Crossroads,
        context: Context::Overworld("Chest_A01_CrossRoads_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    // Stoneheart City
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_SandRelic"),
        drop: Drop::Item(Item::SandRelic, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup51"),
        drop: Drop::Ore(100),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_A01_Stoneheart_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 2),
        locks: &[Lock::Movement(&[walljump!(2, 0), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_A01_City_SRL3"),
        drop: Drop::Ore(400),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 0, 1000),
        drop: Drop::Tunic(Tunic::Orange),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 1, 1000),
        drop: Drop::Tunic(Tunic::Aqua),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 2, 1000),
        drop: Drop::Tunic(Tunic::Royal),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 3, 1000),
        drop: Drop::Tunic(Tunic::Lila),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 4, 5000),
        drop: Drop::Tunic(Tunic::Rainbow),
        locks: &[Lock::Money(5000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 5, 1000),
        drop: Drop::Tunic(Tunic::LightBlue),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 6, 1000),
        drop: Drop::Tunic(Tunic::Violet),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 7, 1000),
        drop: Drop::Tunic(Tunic::Grey),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 8, 1000),
        drop: Drop::Tunic(Tunic::Green),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 9, 1000),
        drop: Drop::Tunic(Tunic::Yellow),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Ari, 10, 1000),
        drop: Drop::Tunic(Tunic::Red),
        locks: &[Lock::Money(1000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup27"),
        drop: Drop::Ore(200),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_A01_City_SRL2"),
        drop: Drop::Ore(300),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Cutscene("NPC/Orip/BP_Orip_Saw/NPC_Orip_Stoneheart"),
        drop: Drop::Item(Item::OddRock, 1),
        // being in debt will not softlock you
        locks: &[Lock::Money(4800)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_A01_City_SRL"),
        drop: Drop::Ore(150),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup45"),
        drop: Drop::Ore(150),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_A01_Stoneheart_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup46"),
        drop: Drop::Ore(100),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup54"),
        drop: Drop::Ore(100),
        locks: &[],
    },
    // the cutest chest in existence
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_A01_Stoneheart_Loot"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Mork, 0, 2800),
        drop: Drop::Spirit(Spirit::PossesedBook),
        locks: &[Lock::Money(2800)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Mork, 1, 2500),
        drop: Drop::Spirit(Spirit::GoldenLust),
        locks: &[Lock::Money(2500)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Mork, 2, 2200),
        drop: Drop::Spirit(Spirit::LifeSteal),
        locks: &[Lock::Money(2200)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Mork, 3, 4000),
        drop: Drop::Item(Item::LargePouch, 1),
        locks: &[Lock::Money(4000)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Mork, 4, 1200),
        drop: Drop::Item(Item::RareSnow, 1),
        locks: &[Lock::Money(1200)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_Book3"),
        drop: Drop::Item(Item::Book, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_Book"),
        drop: Drop::Item(Item::Book, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Dance_Platform_Triceps_Chest"),
        drop: Drop::Item(Item::IceCrystal, 1),
        locks: &[Lock::Emote(Emote::Triceps)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Spirit_A01_FarasGrace"),
        drop: Drop::Spirit(Spirit::FarasGrace),
        locks: &[Lock::Item(Item::Necklace)],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup29"),
        drop: Drop::Ore(150),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup34"),
        drop: Drop::Ore(100),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_Book4"),
        drop: Drop::Item(Item::Book, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_Book5"),
        drop: Drop::Item(Item::Book, 1),
        locks: &[Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)])],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_A01_Stoneheart_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)])],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Pickup_Book2"),
        drop: Drop::Item(Item::Book, 1),
        locks: &[],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Cutscene("NPC/Merchant/NPC_Merchant"),
        drop: Drop::Tunic(Tunic::MerchantsRobe),
        locks: &[Lock::Mork],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Duck2"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[no_walljump!(2, 0)])],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Cutscene("NPC/Onops/MUSIC_Onops/Onop_Musicians/NPC_Onop_IO_Wolfgang"),
        drop: Drop::Ore(500),
        locks: &[
            Lock::Location(Location::RustVillage),
            Lock::Item(Item::ComposerLetter),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_A01_Tunic_AlphaTunic"),
        drop: Drop::Tunic(Tunic::AlphaUmbra),
        locks: &[Lock::Movement(&[walljump!(1, 0), no_walljump!(3, 0)])],
    },
    // Forest Temple
    Check {
        location: Location::WaterLevels,
        context: Context::Overworld("Chest_A01_Nuos_Loot_05"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::WaterLevels,
        context: Context::Overworld("Chest_A01_Nuos_Loot_02"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::WaterLevels,
        context: Context::Overworld("Chest_A01_Nuos_Key"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[],
    },
    Check {
        location: Location::NuosClaw,
        context: Context::Overworld("Chest_A01_Nuos_Loot_01"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::NuosClaw,
        context: Context::Overworld("Chest_A01_Nuos_Key_01"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[],
    },
    Check {
        location: Location::NuosClaw,
        context: Context::Overworld("Chest_A01_Nuos_Key_03"),
        drop: Drop::Item(Item::KeyHolyMaster, 1),
        locks: &[Lock::Item(Item::OldKey)],
    },
    Check {
        location: Location::NuosClaw,
        context: Context::Overworld("Chest_A01_Nuos_Ability_WallRun"),
        drop: Drop::Ability(Ability::WallRun),
        locks: &[Lock::Item(Item::KeyHolyMaster)],
    },
    Check {
        location: Location::WaterLevels,
        context: Context::Overworld("Spirit_A01_ForestGuardian"),
        drop: Drop::Spirit(Spirit::ForestGuardian),
        locks: &[Lock::Movement(&[walljump!(0, 0), no_walljump!(5, 0)])],
    },
    Check {
        location: Location::WaterLevels,
        context: Context::Overworld("Chest_A01_Nuos_Loot"),
        drop: Drop::Item(Item::EmeraldOre, 3),
        locks: &[Lock::Movement(&[walljump!(0, 4), no_walljump!(2, 10)])],
    },
    Check {
        location: Location::Tree,
        context: Context::Overworld("Chest_A01_Nuos_Loot_06"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Tree,
        context: Context::Overworld("Chest_A01_TempleGardens_Sword_SilverBlades"),
        drop: Drop::Weapon(Weapon::SilverBlades),
        locks: &[],
    },
    Check {
        location: Location::Tree,
        context: Context::Overworld("A01_Nuos_EmoteStatue_Wave"),
        drop: Drop::Emote(Emote::Wave),
        locks: &[Lock::Movement(&[no_walljump!(2, 1), walljump!(0, 1)])],
    },
    Check {
        location: Location::Tree,
        context: Context::Overworld("Chest_A01_Nuos_Loot_04"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(2, 1), walljump!(0, 1)])],
    },
    Check {
        location: Location::Tree,
        context: Context::Overworld("Chest_A01_Nuos_Key_02"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[Lock::Movement(&[no_walljump!(2, 1), walljump!(0, 1)])],
    },
    Check {
        location: Location::ForestDucks,
        context: Context::Overworld("Dance_Platform_Hello2_Chest"),
        drop: Drop::Item(Item::Apple, 1),
        locks: &[Lock::Movement(&[no_walljump!(2, 1), walljump!(0, 1)])],
    },
    Check {
        location: Location::ForestDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[no_walljump!(2, 1), walljump!(0, 1)])],
    },
    Check {
        location: Location::ForestDucks,
        context: Context::Overworld("Chest_A01_Nuos_MasterKey"),
        drop: Drop::Item(Item::KeyHolyMaster, 1),
        locks: &[Lock::Item(Item::OldKey)],
    },
    Check {
        location: Location::Gruh,
        context: Context::Cutscene("Cinematics/NuosTempleEnd/Nuos_Temple_End_Controller"),
        drop: Drop::Item(Item::KeyUthasTemple, 1),
        locks: &[],
    },
    // Tavern
    Check {
        location: Location::Stoneheart,
        context: Context::Specific(Case::Bremur, 69),
        drop: Drop::Item(Item::KeyGraveyardKey, 1),
        locks: &[
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Specific(Case::Bremur, 70),
        drop: Drop::Weapon(Weapon::BremurFamilySwords),
        locks: &[
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
            Lock::Item(Item::BremurPicture),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_Master_A01_StoneheartCity_GraveyardKey"),
        drop: Drop::Item(Item::DeadRat, 1),
        locks: &[
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_Master_A01_StoneheartCity_GraveyardKey2"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Overworld("Chest_A01_Stoneheart_Tunic_MerchantsRobe"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Cutscene("NPC/Onops/Onop_Thief/NPC_Onop_Thief"),
        drop: Drop::Item(Item::SmallPouch, 1),
        locks: &[
            Lock::Money(2000),
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Poi, 0, 150),
        drop: Drop::Item(Item::FireEssence, 1),
        locks: &[
            Lock::Money(150),
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::Stoneheart,
        context: Context::Shop(Shop::Poi, 1, 1500),
        drop: Drop::Item(Item::FireEssence, 2),
        locks: &[
            Lock::Money(1500),
            Lock::Location(Location::Gruh),
            Lock::Movement(&[walljump!(0, 0), no_walljump!(1, 0)]),
        ],
    },
    // Temple Gardens
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Pickup2"),
        drop: Drop::Ore(100),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Specific(Case::Angels, 70),
        drop: Drop::Item(Item::FireEssenceSlot, 2),
        locks: &[Lock::EvolairTunic],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_04"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_06"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_07"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_08"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_RareSnow"),
        drop: Drop::Item(Item::DeadRat, 1),
        locks: &[],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Cutscene("NPC/Nilo/NPC_Nilo"),
        drop: Drop::Tunic(Tunic::ForestTunic),
        locks: &[],
    },
    // editing the savegame doesn't edit unlike other shops
    // Check {
    //     location: Locations::TempleGardens,
    //     context: Context::Shop(Shop::Nilo, 0, 1500),
    //     drop: Drop::Item(Items::EmeraldOre, 1),
    //     locks: &[Lock::Money(1500)],
    // },
    // Check {
    //     location: Locations::TempleGardens,
    //     context: Context::Shop(Shop::Nilo, 1, 800),
    //     drop: Drop::Item(Items::SapphireOre, 1),
    //     locks: &[Lock::Money(800)],
    // },
    // Check {
    //     location: Locations::TempleGardens,
    //     context: Context::Shop(Shop::Nilo, 2, 500),
    //     drop: Drop::Item(Items::RubyOre, 1),
    //     locks: &[Lock::Money(500)],
    // },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Dance_Platform_Wave_Chest"),
        drop: Drop::Item(Item::RottenApple, 1),
        locks: &[
            Lock::Movement(&[no_walljump!(0, 4)]),
            Lock::Emote(Emote::Wave),
        ],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Sword_Shanks"),
        drop: Drop::Weapon(Weapon::SteelShanks),
        locks: &[Lock::Movement(&[walljump!(1, 0)])],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Dance_Platform_Applause_Tunic_BananaKing"),
        drop: Drop::Tunic(Tunic::BananaKing),
        locks: &[
            Lock::Movement(&[walljump!(2, 0)]),
            Lock::Emote(Emote::Applause),
        ],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Spirit_A01_HolyCentry"),
        drop: Drop::Spirit(Spirit::HolyCentry),
        locks: &[Lock::Movement(&[walljump!(1, 0)])],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Chest_A01_TempleGardens_Loot_05"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[walljump!(2, 0)])],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Pickup"),
        drop: Drop::Ore(500),
        locks: &[Lock::Movement(&[walljump!(2, 0)])],
    },
    Check {
        location: Location::TempleGardens,
        context: Context::Overworld("Duck3"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[walljump!(2, 0)])],
    },
    // Abandoned Path
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Chest_A01_Graveyard_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("A01_Graveyard_EmoteStatue_Aggressive"),
        drop: Drop::Emote(Emote::Aggressive),
        locks: &[Lock::Movement(&[no_walljump!(0, 2)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Pickup_Necklace"),
        drop: Drop::Item(Item::Necklace, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 2)])],
    },
    // Uthas Temple
    Check {
        location: Location::UthasStart,
        context: Context::Overworld("Spirit_A01_LoveFlower"),
        drop: Drop::Spirit(Spirit::LoveFlower),
        locks: &[Lock::Movement(&[walljump!(1, 0)])],
    },
    Check {
        location: Location::UthasStart,
        context: Context::Overworld("Chest_A01_Uthas_Loot_03"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[],
    },
    Check {
        location: Location::UthasStart,
        context: Context::Overworld("Chest_A01_Uthas_Key_04"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[],
    },
    Check {
        location: Location::UthasStart,
        context: Context::Overworld("Chest_A01_Uthas_Loot_02"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[Lock::Location(Location::UthasBracelet)],
    },
    Check {
        location: Location::UthasDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[walljump!(2, 0), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_Key_02"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[],
    },
    Check {
        location: Location::UthasPuzzle,
        context: Context::Overworld("Chest_A01_Uthas_Key_01"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[Lock::Movement(&[
            no_walljump!(1, 0),
            walljump!(0, 1),
            no_walljump!(0, 3),
        ])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_Loot_04"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(0, 3)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_Loot"),
        drop: Drop::Weapon(Weapon::PeaceKeepers),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(0, 3)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("A01_Uthas_EmoteStatue_Photo"),
        drop: Drop::Emote(Emote::Photo),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(0, 3)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_Loot_01"),
        drop: Drop::Ability(Ability::DoubleJump),
        locks: &[
            Lock::Movement(&[walljump!(0, 1), no_walljump!(0, 3)]),
            Lock::Item(Item::KeyHolyMaster),
        ],
    },
    Check {
        location: Location::UthasCombat,
        context: Context::Overworld("Chest_A01_Uthas_MasterKey"),
        drop: Drop::Item(Item::KeyHolyMaster, 1),
        locks: &[],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("A01_Uthas_EmoteStatue_Party"),
        drop: Drop::Emote(Emote::Party),
        locks: &[Lock::Movement(&[no_walljump!(1, 1)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_Loot_05"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(1, 1)])],
    },
    Check {
        location: Location::UthasPlatforming,
        context: Context::Overworld("Chest_A01_Uthas_Key_03"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[Lock::Movement(&[no_walljump!(1, 4), walljump!(1, 2)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_Loot_06"),
        drop: Drop::Item(Item::EmeraldOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(0, 3)])],
    },
    Check {
        location: Location::UthasBracelet,
        context: Context::Overworld("Chest_A01_Uthas_MasterKey2"),
        drop: Drop::Item(Item::KeyHolyMaster, 1),
        locks: &[
            Lock::Location(Location::UthasEnd),
            Lock::Movement(&[no_walljump!(0, 2)]),
        ],
    },
    Check {
        location: Location::UthasEnd,
        context: Context::Overworld("Chest_A01_Uthas_Key_05"),
        drop: Drop::Item(Item::OldKey, 1),
        locks: &[Lock::Movement(&[no_walljump!(1, 3), walljump!(1, 0)])],
    },
    Check {
        location: Location::UthasEnd,
        context: Context::Cutscene("Cinematics/UthasTempleEnd/Uthas_Temple_End_Controller"),
        drop: Drop::Item(Item::KeyGodMaster, 1),
        locks: &[Lock::Item(Item::OldKey), Lock::Item(Item::KeyHolyMaster)],
    },
    Check {
        location: Location::SanctuaryStone,
        context: Context::Cutscene("Cinematics/LeaveTemple/LeaveTemple_Controller"),
        drop: Drop::Item(Item::SanctuaryStone, 1),
        locks: &[],
    },
    // Tower
    // for most of these you can climb the tower and drop down
    // i can tell if you don't have a lot of movement this'll be tedious...
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("A01_Graveyard_EmoteStatue_No"),
        drop: Drop::Emote(Emote::No),
        locks: &[],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Pickup_Rose2"),
        drop: Drop::Item(Item::Rose, 1),
        locks: &[Lock::Movement(&[walljump!(0, 2), no_walljump!(0, 3)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Pickup_BremurPicture"),
        drop: Drop::Item(Item::BremurPicture, 1),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(0, 2)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Chest_A01_Graveyard_IceDestroyers"),
        drop: Drop::Weapon(Weapon::IceDestroyers),
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Chest_A02_Tunic_HolyAttire"),
        drop: Drop::Tunic(Tunic::OnopCoat),
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Pickup_Rose"),
        drop: Drop::Item(Item::Rose, 1),
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Chest_A01_Graveyard_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Chest_A01_Graveyard_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Overworld("Dance_Platform_Levitation_Chest"),
        drop: Drop::Item(Item::SeagulSoup, 1),
        locks: &[
            Lock::Emote(Emote::Levitation),
            Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)]),
        ],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Cutscene("NPC/Onops/MUSIC_Onops/Onop_Musicians/NPC_Onop_IO_Bech"),
        drop: Drop::Ore(500),
        locks: &[
            Lock::Location(Location::RustVillage),
            Lock::Item(Item::ComposerLetter),
            Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)]),
        ],
    },
    Check {
        location: Location::AbandonedPath,
        context: Context::Cutscene("Cinematics/VesselVon/VesselVon_Controller"),
        drop: Drop::Item(Item::BeiraVessel, 1),
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    // Firefall River
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Dance_Platform_HatKid_Chest"),
        drop: Drop::Weapon(Weapon::EmberTwins),
        locks: &[
            Lock::Emote(Emote::HatKid),
            Lock::Movement(&[no_walljump!(1, 4)]),
        ],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Pickup_A06_SRL4"),
        drop: Drop::Ore(250),
        locks: &[Lock::Movement(&[no_walljump!(1, 4)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Pickup_A06_SRL5"),
        drop: Drop::Ore(200),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Chest_A06_River_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 0), no_walljump!(0, 1)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Chest_A06_River_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Pickup_A06_SRL2"),
        drop: Drop::Ore(200),
        locks: &[Lock::Movement(&[no_walljump!(1, 3)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Pickup_A06_SRL"),
        drop: Drop::Ore(300),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Pickup_A06_SRL3"),
        drop: Drop::Ore(300),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::FirefallSpiritHunter,
        context: Context::Overworld("Pickup8"),
        drop: Drop::Ore(200),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    // i can't find pickup 6
    Check {
        location: Location::Bunny,
        context: Context::Overworld("Pickup11"),
        drop: Drop::Ore(100),
        locks: &[],
    },
    Check {
        location: Location::Bunny,
        context: Context::Cutscene("NPC/Onops/Onop_Speedo/NPC_Onop_Speedo"),
        drop: Drop::Ability(Ability::Sprint),
        locks: &[Lock::Money(8000)],
    },
    Check {
        location: Location::Bunny,
        context: Context::Overworld("Pickup9"),
        drop: Drop::Ore(150),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Bunny,
        context: Context::Overworld("Pickup12"),
        drop: Drop::Ore(150),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Bunny,
        context: Context::Overworld("Dance_Platform_Windmill_Chest"),
        drop: Drop::Item(Item::RareCheese, 1),
        locks: &[
            Lock::Emote(Emote::Windmill),
            Lock::Movement(&[no_walljump!(1, 4)]),
        ],
    },
    Check {
        location: Location::Bunny,
        context: Context::Cutscene("NPC/Onops/Onop_Onari/NPC_Master_Onari"),
        drop: Drop::Tunic(Tunic::BunnySuit),
        locks: &[Lock::Money(2000), Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Bunny,
        context: Context::Overworld("Chest_A06_River_Loot_02"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Bunny,
        context: Context::Overworld("Pickup10"),
        drop: Drop::Ore(150),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Bunny,
        context: Context::Overworld("A06_Firefall_EmoteStatue_KungFu"),
        drop: Drop::Emote(Emote::KungFu),
        locks: &[Lock::Movement(&[no_walljump!(0, 1)])],
    },
    Check {
        location: Location::Bunny,
        context: Context::Cutscene("NPC/Mira_Mia/NPC_Mia_Firefall"),
        drop: Drop::Ore(5000),
        locks: &[Lock::Location(Location::RustVillage)],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("Pickup58"),
        drop: Drop::Ore(150),
        locks: &[],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("Dance_Platform_Party_Chest_Spirit_HammerKing"),
        drop: Drop::Spirit(Spirit::HammerKing),
        locks: &[
            Lock::Emote(Emote::Party),
            Lock::Movement(&[no_walljump!(1, 0)]),
        ],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("Spirit_A06_FlyingOnop"),
        drop: Drop::Spirit(Spirit::FlyingOnop),
        locks: &[Lock::Location(Location::RustVillage)],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("Pickup2"),
        drop: Drop::Ore(250),
        locks: &[],
    },
    // myurder
    Check {
        location: Location::LakeMolva,
        context: Context::Cutscene("NPC/Onops/Onop_Codi/NPC_Onop_Codi"),
        drop: Drop::Item(Item::HouseKey, 1),
        locks: &[Lock::Location(Location::RustVillage)],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Cutscene("NPC/Onops/MUSIC_Onops/Onop_Musicians/NPC_Onop_IO_Viveldi"),
        drop: Drop::Ore(500),
        locks: &[
            Lock::Location(Location::RustVillage),
            Lock::Item(Item::ComposerLetter),
        ],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("Chest_A06_Lake_Loot_01"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::FirefallDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("A06_Firefall_EmoteStatue_Triceps"),
        drop: Drop::Emote(Emote::Triceps),
        locks: &[],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Overworld("Chest_A06_Lake_Loot_03"),
        drop: Drop::Item(Item::SapphireOre, 1),
        locks: &[],
    },
    Check {
        location: Location::LakeMolva,
        context: Context::Cutscene("NPC/Onops/NPC_Onop_SectMember_Tunic"),
        drop: Drop::Tunic(Tunic::SectMember),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(2, 0)])],
    },
    Check {
        location: Location::SteamHouseDucks,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[Lock::Movement(&[walljump!(2, 3)])],
    },
    Check {
        location: Location::SteamHouse,
        context: Context::Cutscene("NPC/Mira_Mia/NPC_Mira"),
        drop: Drop::Item(Item::KeySteam, 1),
        locks: &[],
    },
    Check {
        location: Location::SteamHouse,
        context: Context::Overworld("Chest_A06_SteamHouse_Tunic_SteamSuit"),
        drop: Drop::Tunic(Tunic::SteamWorkerTunic),
        locks: &[Lock::Movement(&[no_walljump!(1, 1)])],
    },
    Check {
        location: Location::SteamHousePlatforming,
        context: Context::Cutscene("NPC/Mira_Mia/NPC_Mia"),
        drop: Drop::Weapon(Weapon::IronJustice),
        locks: &[],
    },
    Check {
        location: Location::Sirion,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Cutscene("Cinematics/RustCity_Von/RustCityVon_Controller"),
        drop: Drop::Item(Item::KeyFireMaster, 1),
        locks: &[],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Overworld("Pickup21"),
        drop: Drop::Ore(400),
        locks: &[],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Overworld("A06_RustCity_EmoteStatue_Applause"),
        drop: Drop::Emote(Emote::Applause),
        locks: &[],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Cutscene("NPC/Onops/Onop_Mon/NPC_Onop_Mon"),
        drop: Drop::Item(Item::HouseContract, 1),
        locks: &[Lock::Item(Item::HouseKey)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Overworld("Dance_Platform_No_Chest"),
        drop: Drop::Tunic(Tunic::Pumpkin),
        locks: &[Lock::Emote(Emote::No)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Cutscene("NPC/Onops/MUSIC_Onops/Onop_Compositor/NPC_Onop_Compositor"),
        drop: Drop::Item(Item::ComposerLetter, 4),
        locks: &[],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Specific(Case::Paulale, 69),
        drop: Drop::Tunic(Tunic::PerformerCostume),
        // just Bech's requirements since everyone else is easily accessible
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Specific(Case::Paulale, 70),
        drop: Drop::Item(Item::SapphireOre, 2),
        // just Bech's requirements since everyone else is easily accessible
        locks: &[Lock::Movement(&[walljump!(1, 1), no_walljump!(4, 0)])],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Cutscene("NPC/Onops/Onop_Barri/NPC_Master_BarriStage2"),
        drop: Drop::Weapon(Weapon::KinaDefenders),
        locks: &[Lock::Item(Item::Rose)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Cutscene("NPC/Onops/Onop_Nuno/NPC_Onop_Nuno"),
        drop: Drop::Ore(3000),
        locks: &[Lock::Item(Item::RareSnow)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Overworld("Dance_Platform_Aggresive_Chest"),
        drop: Drop::Item(Item::RareGlasses, 1),
        locks: &[Lock::Emote(Emote::Aggressive)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Shop(Shop::Poti, 0, 3000),
        drop: Drop::Spirit(Spirit::OnopSiblings),
        locks: &[Lock::Money(3000)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Shop(Shop::Poti, 1, 2200),
        drop: Drop::Spirit(Spirit::MoiTheDreadful),
        locks: &[Lock::Money(2200)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Shop(Shop::Poti, 2, 12500),
        drop: Drop::Weapon(Weapon::ShadowCasters),
        locks: &[Lock::Money(12500)],
    },
    Check {
        location: Location::RustVillage,
        context: Context::Shop(Shop::Poti, 3, 8000),
        drop: Drop::Item(Item::ExtraLargePouch, 1),
        locks: &[Lock::Money(8000)],
    },
    // Beira's Shrine
    Check {
        location: Location::Beira,
        context: Context::Overworld("Spirit_A01_AngryAmbusher"),
        drop: Drop::Spirit(Spirit::AngryAmbusher),
        locks: &[],
    },
    Check {
        location: Location::Beira,
        context: Context::Specific(Case::Angels, 71),
        drop: Drop::Item(Item::FireEssenceSlot, 2),
        locks: &[Lock::Item(Item::OddRock)],
    },
    Check {
        location: Location::Beira,
        context: Context::Overworld("Chest_A01_Graveyard_Key_01"),
        drop: Drop::Item(Item::RubyOre, 1),
        locks: &[],
    },
    Check {
        location: Location::Beira,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[],
    },
    Check {
        location: Location::Queen,
        context: Context::Overworld("Duck"),
        drop: Drop::Duck,
        locks: &[],
    },
    Check {
        location: Location::PathOfVictory,
        context: Context::Overworld("Chest_Master"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[],
    },
    Check {
        location: Location::ArigosChallenge,
        context: Context::Overworld("Chest_Master"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 0)])],
    },
    Check {
        location: Location::BorisasFate,
        context: Context::Overworld("Chest_Master_Loot_04_V2"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 0), no_walljump!(2, 0)])],
    },
    Check {
        location: Location::BorisasFate,
        context: Context::Overworld("Chest_Master_Loot_04_V21"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[walljump!(0, 1), no_walljump!(2, 0)])],
    },
    Check {
        location: Location::JuliansSong,
        context: Context::Overworld("Chest_Master"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::JuliansSong,
        context: Context::Overworld("Chest_Master2"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[no_walljump!(0, 3)])],
    },
    Check {
        location: Location::Alchemist,
        context: Context::Overworld("Chest_Master_Void_Santi_03"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[walljump!(2, 0)])],
    },
    Check {
        location: Location::Alchemist,
        context: Context::Overworld("Chest_Master_Void_Santi_02"),
        drop: Drop::Item(Item::VoidOre, 1),
        locks: &[Lock::Movement(&[walljump!(1, 3)])],
    },
    // don't ask. if you want to know look through #clips-and-screenshots
    Check {
        location: Location::TheVoid,
        context: Context::Specific(Case::AllVoids, 69),
        drop: Drop::Tunic(Tunic::SilverCloack),
        locks: &[],
    },
];
